// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iahtdkressnntmwluedk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhaHRka3Jlc3NubnRtd2x1ZWRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MDM0MzMsImV4cCI6MjA2NjM3OTQzM30.HkZ8O1bhDvN9bQIzDxMWi3v7RlZL3UaJ8CvboQac65Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);